#ifndef AZURE_CONFIGURATION_H
#define AZURE_CONFIGURATION_H

#include "EEPROMInterface.h"

#define AZ_IOT_HUB_ZONE_IDX EEPROM_DEVICE_CONNECTION_ZONE_IDX
#define AZ_IOT_HUB_MAX_LEN EEPROM_DEVICE_CONNECTION_MAX_LEN
#define AZ_IOT_X509_MAX_LEN EEPROM_X509_MAX_LEN
#define DPS_UDS_ZONE_IDX STSAFE_ZONE_6_IDX
#define DPS_UDS_MAX_LEN 64

#define WEB_SETTING_IOT_DEVICE_CONN_STRING  0x00000001
#define WEB_SETTING_IOT_CERT                0x00000002
#define WEB_SETTING_IOT_DPS_SYMMETRIC_KEY   0x00000004

#endif