name=ArduinoMDNS 
version=1.1.0
author=Georg Kaindl <info@gkaindl.com>
maintainer=AaronWangTT
sentence=mDNS Library for Arduino
paragraph=Supports mDNS (registering services) and DNS-SD (service discovery)
category=Communication
url=https://github.com/AaronWangTT/ArduinoMDNS
architectures=*
includes=ArduinoMDNS.h
